FROM node:16.13-alpine3.14 AS alpine
RUN apk --no-cache --virtual build-dependencies add \
    bash \
    git \
    openssh \
    python3 \
    make \
    g++
WORKDIR /app

COPY package.json .
COPY yarn.lock .
RUN yarn
COPY . .

ARG PINATA_API_KEY
ARG PINATA_API_SECRET_KEY
ARG PINATA_GATEWAY
ARG PINATA_ACCESS_TOKEN
ARG NEXT_PUBLIC_REST_ENDPOINT
ARG NEXT_PUBLIC_GRAPHQL_ENDPOINT

ENV PINATA_API_KEY=$PINATA_API_KEY
ENV PINATA_API_SECRET_KEY=$PINATA_API_SECRET_KEY
ENV PINATA_GATEWAY=$PINATA_GATEWAY
ENV PINATA_ACCESS_TOKEN=$PINATA_ACCESS_TOKEN
ENV NEXT_PUBLIC_REST_ENDPOINT=$NEXT_PUBLIC_REST_ENDPOINT
ENV NEXT_PUBLIC_GRAPHQL_ENDPOINT=$NEXT_PUBLIC_GRAPHQL_ENDPOINT

RUN yarn build
EXPOSE 3000
CMD ["yarn", "start"]
