import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect } from 'react'
import styles from '../styles/Home.module.css'
import {useWeb3} from '../composables/useWeb3'
import { getInjected } from '@snapshot-labs/lock/src/utils';
import './_app'

const Home: NextPage = () => {

  function connectWallet() {
    const { login } = useWeb3();

    // Auto connect if previous session was connected
    if (window?.parent === window)
    //@ts-ignore
      auth.getConnector().then(connector => {
        if (connector) return login(connector);
      });

    // Auto connect with gnosis-connector when gnosis safe is detected
    login('gnosis');

    const injected =  getInjected();
    // edge case if MM and CBW are both installed
    //@ts-ignore
    if (injected.id === 'metamask') return;
    // Auto connect when coinbase wallet is detected
    //@ts-ignore
    if (injected.id === 'coinbase') return login('injected');
  }
  useEffect(() => {
      connectWallet();
  },[])


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}

export default Home
